### ISSUE TITLE
Login screen. Cursor

### ISSUE THREAD

**Issue by moralezWS** [erzonline/community#10]
**Опиши баг**
В активном пустом поле ввода логина/пароля отсутствует мигание курсора. (аналогичный баг после ввода второго символа)

**Как повторить баг**
1. Нажимаем на пусто окно логина/пароля
2. Курсор отсутствует (не мигает)

**Ожидаемое поведение**
При нажатии на поле ввода логина/пароля должен появляться мигающий курсор (вертикальная черта).

**Скриншоты и видео**
![изображение](https://user-images.githubusercontent.com/107573929/173891804-437ea34c-5171-4a1c-9cb6-abe563a125f0.png)

**Desktop (заполни на чем ты играл, когда нашел баг):**

    OS: Windows 10, x64
    Client Version: Release Okean

**Comment by ARyaskov** [comment]
В новой версии добавили мигание курсора, выбор через TAB/SHIFT-TAB, выделение активного поля
<img width="547" alt="Screen Shot 2022-06-18 at 2 58 07 AM" src="https://user-images.githubusercontent.com/3934848/174413831-587ad41a-263b-4869-a64f-42c78b95e00a.png">

**Comment by moralezWS** [comment]
баг после ввода второго символа пофикшен

Аналогичный баг с отсутствием курсора остался после 5, 13, 18, 26 символа
