### ISSUE TITLE
Sand duplication

### ISSUE THREAD

**Issue by moralezWS** [erzonline/community#13]
**Опиши баг**
Одна единица сыпучки размножается при падении больше чем на 1  клетку.

**Как повторить баг**
Напиши порядок действий приводящий к багу:
1. Выкапываем пространство ниже блока сыпучки.
2. Запоминаем положение песка и его количество.
3. Выкапываем клетку под блоком сыпучки, чтобы она упала вниз.
4. Видим баг: количесвто песка увеличилось

**Ожидаемое поведение**
При падении одна единица (1 клетка) сыпучки должна падать строго вниз (с учётом физики) и оставаться в единичном экземпляре (1 клетка).

**Скриншоты и видео**
![изображение](https://user-images.githubusercontent.com/107573929/173896771-2490b170-b69f-4f2d-bf6b-d4b46b50e5a0.png)
![изображение](https://user-images.githubusercontent.com/107573929/173896811-6d94f17e-0a77-4fe5-a09d-1ad7cae39ff3.png)

**Desktop (заполни на чем ты играл, когда нашел баг):**

    OS: Windows 10, x64
    Client Version: Release Okean

**Comment by ARyaskov** [comment]
В новой версии одиночная сыпучка ведёт себя правильно
<img width="452" alt="Screen Shot 2022-06-18 at 2 54 26 AM" src="https://user-images.githubusercontent.com/3934848/174413698-a39ac862-0721-4a6d-a091-9b160af42891.png">
<img width="513" alt="Screen Shot 2022-06-18 at 2 54 47 AM" src="https://user-images.githubusercontent.com/3934848/174413701-dbc4dd59-6e35-4748-a33f-3741b795bdc7.png">
