### ISSUE TITLE
Movement is broken on digging mode near black rock

### ISSUE THREAD

**Issue by Gitnube** [erzonline/community#17]
**Описание**
Если в режиме копания включен тип контроллера "Smart" и упереться роботом в черноскал, то робот зависает на одном месте и больше никуда не движется.

**Как повторить баг**
1. Ставишь тип контроллера "Smart"
2. Включаешь режим копания
3. Упираешься в черноскал
4. Выключаешь режим копания
5. Робот не реагирует на движение контроллера

**Ожидаемое поведение**
Робот отъезжает от черноскала, когда отводишь ползунок контроллера в сторону от него

**Видео**
https://youtu.be/3dP85-w7qsE

**Desktop:**
- OS: Windows 10, x64
- Client Version: Release Okean

**Comment by ENCRYPTEDFOREVER** [comment]
Скорее всего [дубль](https://github.com/erzonline/community/issues/3#issue-1267596384), копание ломаться может в разных местах, с характерным зависанием маркера пути
