### ISSUE TITLE
Movement. Tap mode for PC

### ISSUE THREAD

**Issue by moralezWS** [erzonline/community#27]
**Опиши фичу**
Tap режим для PC версий должен работать всё время в режимах  Smart и Stupid joystic.

**Ожидаемое поведение**
При нажатии курсором на экран робот должен двигаться в указанную клетку, при активном режиме Smart или Stupid joystic.

**Desktop (заполни на чем ты играл, когда нашел баг):**
OS: Windows 10, x64
Client Version: Release GAVNO

**Comment by glebthebread** [comment]
Попробуем реализовать к следующему резизу.
