### ISSUE TITLE
feature of the phone perception of the application

### ISSUE THREAD

**Issue by Rom4ik01** [erzonline/community#28]
**Опиши баг**
Ошибка восприятия осью приложения как игра

**Как повторить баг**
Установить приложение на телефон

**Ожидаемое поведение**
Приложение автоматически добавляется в Game Launcher

**Скриншоты и видео**
-видео при ручном добавлении в гаме лаунчер
https://youtu.be/eWbMrWjvH2s
-видео какой функционал теряется (малая его часть)(на примере стороннего приложения)
https://youtu.be/kXnHqa_VlWI

**Smartphone (заполни на чем ты играл. когда нашел баг):**
 - Device: [Samsung A51] 
 - OS: [Android 12]
 - Version [Erz (2022.5)], прошлые также

**Дополнительные подробности/советы по исправлению**
Где-то читал что это надо прописывать в манифесте

**Comment by ENCRYPTEDFOREVER** [comment]
Это решают разрабы лаунчеров и прочих вещей, они должны добавить имя пакета игры в список, собственно, "игр"

**Comment by Rom4ik01** [comment]
Идем от обратного, тут https://translated.turbopages.org/proxy_u/en-ru.ru.0d40732c-62b54f1c-cb13002d-74722d776562/https/stackoverflow.com/questions/50174122/non-game-app-gets-treated-as-game-by-samsung-game-launcher
Наоборот ругаются что их приложение определяется как игра, что ин доставляет дискомфорт

**Comment by glebthebread** [comment]
Задача на далекое будущее. Доберемся, будем разбираться.

**Comment by Rom4ik01** [comment]
Как снять задачу? Списался с тех.подержкой самсунг ответили что пока приложения нет в маркете нечем помочь не могут

**Comment by glebthebread** [comment]
Да, я закрою
