### ISSUE TITLE
Big joystick

### ISSUE THREAD

**Issue by Lexmarkk** [erzonline/community#31]
**Опиши баг**
Джойстик управления слишком большой.

**Как повторить баг**
Начать двигаться.

**Ожидаемое поведение**
Меньший джойстик, который не закрывает обзор. 

**Скриншоты и видео**
![Screenshot_20220623_210828_online.erz.erz.jpg](https://user-images.githubusercontent.com/108091440/175376462-c80ed371-0da5-4aa8-b662-1b0307a401d3.jpg)

**Smartphone (заполни на чем ты играл. когда нашел баг):**
 - Device: Honor 8s
 - OS: Android 9

**Дополнительные подробности/советы по исправлению**
:)

**Comment by Rom4ik01** [comment]
На данном этапе можно закрывать, нет джойстика нет проблем ))
