### ISSUE TITLE
Tap Mode bug

### ISSUE THREAD

**Issue by Lexmarkk** [erzonline/community#32]
Описание: Если включить режим управления "Tap" и переключиться в режим копания, то робот копать не сможет. 

Повтор бага:
1) Включить режим управления "Tap" 
2) Включить режим копания
3) ткнуть на породу или провести по экрану.

Ожидаемое поведение: Когда включаешь режим копания, должно включаться стандартное управление джойстиком, а когда его включаешь, то возвращается стандартное управление "Tap" 

Скриншоты и видео: https://youtu.be/k2CXPMHg2dU

Smartphone:
 - Device: Honor 8s
 - OS: Android 9

Дополнительные подробности/советы по исправлению:  :)

**Comment by glebthebread** [comment]
Будем обсуждать новое управления к следующему релизу.

**Comment by QA-game** [comment]
не актуально
