### ISSUE TITLE
Digging. Robot twitching

### ISSUE THREAD

**Issue by moralezWS** [erzonline/community#33]
**Опиши баг**
Робот дёргается при копании породы если робот копает в сторону, а не по направлению движения с которого подходил.

**Как повторить баг**
Напиши порядок действий приводящий к багу:
1. Подходишь к некопаемой(черноскал/красноскал) породе со стороны(боком).
2. Копаешь в сторону (право или лево от робота)
3. Робот начинает дёргаться (если не может прокопать породу).

**Ожидаемое поведение**
Робот должен повернуться и копать в указанную сторону, не возвращясь в исходное положение.

**Скриншоты и видео**
![изображение](https://user-images.githubusercontent.com/107573929/175379276-9af687ca-6008-49e0-a5b9-0450b4b75284.png)

**Desktop (заполни на чем ты играл, когда нашел баг):**
OS: Windows 10, x64
Client Version: Release GAVNO

**Comment by glebthebread** [comment]
Вылечится, когда сделаем задачу #41
