### ISSUE TITLE
Settings/main menu interface

### ISSUE THREAD

**Issue by Lexmarkk** [erzonline/community#34]
Описание: Кривой интерфейс в главном менб и настройках. 

Как повторить баг: настройки открыть. 

Ожидаемое поведение: ровный интерфейс

Скриншоты и видео
![Screenshot_20220623_211447_online.erz.erz.jpg](https://user-images.githubusercontent.com/108091440/175379828-57a4a7df-5cc2-4283-821e-c307f38be254.jpg)

![Screenshot_20220623_211155_online.erz.erz.jpg](https://user-images.githubusercontent.com/108091440/175379851-ae00b1ea-c7d2-40df-90ad-65f945247413.jpg)

Smartphone
 - Device: honor 8s
 - OS: Android 9

:)

**Comment by Rom4ik01** [comment]
Также при нажатии в настройках верхней кнопки, в игре нижние кнопки управления накладывает на верхние
![Screenshot_20220623-202351_Erz](https://user-images.githubusercontent.com/108063544/175381729-3ca3e698-0d09-42ca-9c21-9edde12ff2db.jpg)
![Screenshot_20220623-202359_Erz](https://user-images.githubusercontent.com/108063544/175381737-82855926-8e04-449d-a786-53c0c96d138f.jpg)
![Screenshot_20220623-202411_Erz](https://user-images.githubusercontent.com/108063544/175381740-5e6cd71c-0e42-4dfc-afd2-9549659297a8.jpg)

**Comment by glebthebread** [comment]
Будет исправлено с новым интерфейсом авторизации и игры.
