### ISSUE TITLE
no damage, no amount of life

### ISSUE THREAD

**Issue by Rom4ik01** [erzonline/community#35]
**Опиши баг**
Отсутствует урон от "шебня", нет полосы (значения) прочности (ХП, жизни)

**Как повторить баг**
Напиши порядок действий приводящий к багу:
Становишся под сыпучку в виде "шебня" 

**Ожидаемое поведение**
Сыпучка при контакте с роботом должна исчезать, освобаждая место для падения новой сыпучки, при этом наносить урон, также отсутствует отображение сколько прочности осталось, при разных видах сыпучки отнимать разное кол-во прочности

**Видео**
https://youtu.be/fJlIeYbrXvw

**Smartphone (заполни на чем ты играл. когда нашел баг):**
 - Device: Самсунг А51
 - OS: андроид 12
 - Version Ерз (2020.5)

**Дополнительные подробности/советы по исправлению**
Напиши тут.

**Comment by ENCRYPTEDFOREVER** [comment]
Да это ж не баг, а нереализованный (пока) функционал

**Comment by Rom4ik01** [comment]
> 
Это баг, так как песок и лава наносит урон и убивает

**Comment by glebthebread** [comment]
Будем обсуждать с командой ХП бар, как будет работать и отображаться.
