### ISSUE TITLE
control of soft buttons phone

### ISSUE THREAD

**Issue by Rom4ik01** [erzonline/community#37]
**Опиши баг**
При вызове прогграмных кнопок, кнопка назад не работает нигде, игра, чат, меню ...

**Как повторить баг**
Напиши порядок действий приводящий к багу:
Вызываш (проститу... ой не сюда) три-пять программных кнопки и только кнопка < (назад) не работает

**Ожидаемое поведение**
При нажатии на кнопку < (назад) спускалось на уровень ниже, чат->игра, игра->меню, меню->ос

**Скриншоты и видео**
https://youtube.com/shorts/OgAmCOSAXx4?feature=share

**Smartphone (заполни на чем ты играл. когда нашел баг):**
 - Device: Самсунг А51
 - OS: андроид 12
 - Version Erz (2022.5)

**Дополнительные подробности/советы по исправлению**
Напиши тут.

**Comment by kykyst** [comment]
добавить поведение на кнопку назад
