### ISSUE TITLE
The sand will burn, not collapse

### ISSUE THREAD

**Issue by ZulluSuss** [erzonline/community#40]
Описание бага:
Если стоять неподвижно, а на тебя сыпется песок, то тебя просто засыпает. 

Как повторить баг:
Разрушаю кри, который держит кучу песка. 
Бегу на дно (куда он должен упасть).
Стою неподвижно пока не засыплет. 

Ожидаемое поведение
Песок должен разрушаться об робота нанося урон. 

Desktop Win7 x64

Стоять можно сколько угодно, урона нет.
Стоя под ней можно её спокойно есть.
![pesok](https://user-images.githubusercontent.com/108090274/175391499-b620e310-57a9-45ba-b6d8-1e92255948d2.jpg)

**Comment by moralezWS** [comment]
Duplicate #35 #36
