### ISSUE TITLE
Pouring effects for sand-type.

### ISSUE THREAD

**Issue by moralezWS** [erzonline/community#46]
**Опиши баг**
При падении сыпучки, не должна срабатывать анимация её уничтожения при включённом Pouring effects.

**Как повторить баг**
Напиши порядок действий приводящий к багу:
1. Включаем Pouring effects в настройках.
2. Делаем так чтобы сыпучка падала.
3. На месте где была сыпучка возникает анимация её разрушения.

**Ожидаемое поведение**
При падении сыпучки(без уничтожения) не должна показываться анимация разрушения в клетке из которой она упала.

**Скриншоты и видео**
![изображение](https://user-images.githubusercontent.com/107573929/175403477-4b0b3058-821a-4a27-9dfb-715114c11514.png)

**Desktop (заполни на чем ты играл, когда нашел баг):**
OS: Windows 10, x64
Client Version: Release GAVNO

**Comment by glebthebread** [comment]
Думаем, что на сыпучку нужна отдельная анимация.
@terpimost

**Comment by terpimost** [comment]
@glebthebread давайте обсудим голосом, я не очень понял проблему

**Comment by glebthebread** [comment]
@terpimost отбой, тут не тебе
