### ISSUE TITLE
Current coordinate.

### ISSUE THREAD

**Issue by moralezWS** [erzonline/community#50]
**Опиши фичу**
Нужно добавить отображение текущей координаты робота под количеством кристаллов.
Нужно добавить возможность убрать координаты робота с экрана в меню.
Отображение/скрытие координат должно запоминаться клиентом (храниться в конфиге).

**Ожидаемое поведение**
Нужно видеть текущую координату робота.
Нужно скрывать текущую координату робота для режима "стример".

**Скриншоты и видео**
![изображение](https://user-images.githubusercontent.com/107573929/175422789-04ed9b62-cb18-438a-940c-13a58f41258d.png)

**Comment by kykyst** [comment]
+ придумать где пинг и фпс отображать\

**Comment by terpimost** [comment]
Есть план сделать системное техническое окно
