### ISSUE TITLE
Android Bangs Neformala.

### ISSUE THREAD

**Issue by DAZGRIT** [erzonline/community#51]
Андройдовская челка неформала.

Описание бага:
на марки и модели телефона системы андроид blackview bv9600 присутствует "челка" под которой скрывается часть интерфейса.

Как повторить баг:
необходимо купить телефон марки и модели blackview bv9600 и запустить игру.

Напиши порядок действий приводящий к багу:
1. Берешь свой телефон марки и модели blackview bv9600 (андроид)
2. запускаешь ERZ
3. Видишь потерянный за "челкой" интерфейс.

Ожидаемое поведение:
Интерфейс использует пространство справа или слева от "челки" или под ней.

Скриншоты:
Внешний вид телефона
![image](https://user-images.githubusercontent.com/107484167/175493689-acf8491f-220a-43e2-a9d1-20a4948598ed.png)
Дисплей - 1080:2248 (размер челки не нашел)
Smartphone:
 - Device: blackview bv9600
 - OS: Android
 - Browser stock browser
 - Version [ВСЕ]
---------------------------------------------------------
После фикса можно написать мне, как обладателю челки неформала, (-_DAZ-GRIT_-#8021) в ДС, с целью проверки или иного вопроса.

**Comment by Rom4ik01** [comment]
У всех телефонов разные челки и камеры на экране,  может то что с низу и с верху раскидать по бокам

**Comment by terpimost** [comment]
@DAZGRIT могли бы вы прислать фотографию того как это выглядит на настоящем устройстве?

**Comment by ENCRYPTEDFOREVER** [comment]
> @DAZGRIT могли бы вы прислать фотографию того как это выглядит на настоящем устройстве?

Часть контента просто не видна под "чёлкой", выгдлядит ровно так, как это можно себе представить

**Comment by Gitnube** [comment]
Устройство: Honor JSN-L21
Такая же проблема. Скриншот ниже
![Screenshot_20220703_101629_online erz erz](https://user-images.githubusercontent.com/37284250/177023131-2f7b909d-9dc6-44c7-8da1-da186f626efd.jpg)
