### ISSUE TITLE
after death, not on respawn

### ISSUE THREAD

**Issue by Rom4ik01** [erzonline/community#52]
**Опиши баг**
При нажимании кнопк "воом" возле скалы, быстро выходим, ждем 2-3 сек заходим, появляемся там же(скала разрушена), не надо переть с респа

**Как повторить баг**
Напиши порядок действий приводящий к багу:
1. Подходиш к скале
2. Жмеш воом
3. быстро жмеш меню
4. еще быстрее жмеш логаут
5. ждем 2-3 сек
6. кнопаем логин
7. вуаля мы тамже

**Ожидаемое поведение**
После любой смерти появлятся на респе

**Скриншоты и видео**
https://youtube.com/shorts/MJ7KtelYG_E?feature=share

**Smartphone (заполни на чем ты играл. когда нашел баг):**
 - Device: Гнусмас а51
 - OS: дроид 12
 - Version билд текуший на 24.06.2022

**Дополнительные подробности/советы по исправлению**
Напиши тут.

**Comment by ENCRYPTEDFOREVER** [comment]
Уточнение: сервер перемещает бота на респ, если последний находится онлайн через +/- 5 секунд после смерти. Чтобы избежать перемещения нужно просто не быть онлайн в этот момент...
То есть можно на протяжении чуть меньше 5-ти секунд быстро релогиниться, взрываясь 2 раза в секунду, а потом на эти самые 5 секунд (от последнего бума) уйти в подполье (в оффлайн), а далее цикл можно повторить

**Comment by glebthebread** [comment]
Будет исправлено с новой логикой респавна ботов
