### ISSUE TITLE
Cobblestones do not roll properly

### ISSUE THREAD

**Issue by ZulluSuss** [erzonline/community#53]
**Названия задач на баг (issues) должны быть на английском!
Булыжника не правильно падают. 

**Опиши баг**
На видосе видно, что я имею ввиду. 

**Как повторить баг**
Когда булыжники лежат слева и справа от робота, 
Копаю породу (в моём случае булыжник) под собой. Оба булыжника, левый и правый, падают в ямку одновременно!
Куда пропадает один из них?

**Ожидаемое поведение**
Булыжники должны падать в ямку по одному.  

**Скриншоты и видео**

https://youtu.be/rf45SBgTMCM

**Desktop (заполни на чем ты играл, когда нашел баг):**
Win7 x64

**Comment by glebthebread** [comment]
Дубликат
