### ISSUE TITLE
Сhange nickname location

### ISSUE THREAD

**Issue by Gitnube** [erzonline/community#57]
**Описание фичи:**
1. Добавьте возможность скрыть ник или лучше перенесите его над роботом.
2. Если ник останется, добавьте масштабирование ника.
3. При мелком масштабировании добавьте контрастное отображение робота (например, в виде красной точки)

**Проблема:**
1. Ник загораживает много места при мелком масштабировании. 
2. Ник не дает представление о точной позиции робота при мелком масштабировании. 
3. В тусклом окружении сложно увидеть робота при мелком масштабировании.

**Обоснование:**
1. Почему над роботом разместить его удобнее: потому что обычно копают сверху вниз, в связи с чем сверху над роботом свободное место, а внизу - породы, которые нужно рассматривать.

**Comment by glebthebread** [comment]
Имена теперь скрываются когда отдаляешь карту
