### ISSUE TITLE
Sand pours from both sides at once.

### ISSUE THREAD

**Issue by ZulluSuss** [erzonline/community#59]
**Названия задач на баг (issues) должны быть на английском!
Песок сыпется в ямку из одной клетки сразу с двух строк.

**Опиши баг**
Такая же проблема описана мною в  # 53

**Ожидаемое поведение**
песок в выкопанную ямку должен падать сначала с одной стороны, потом с другой. 

**Видео**
https://youtu.be/DXy6MsXBc1s

**Desktop (заполни на чем ты играл, когда нашел баг):**
Win7 x64

**Comment by ENCRYPTEDFOREVER** [comment]
При этом происходит антидюп для восстановаления баланса во вселенной

**Comment by Rom4ik01** [comment]
В версии 2022.6 происходит тоже самое с валунами (видимо вся сыпучка так забагована)
https://youtu.be/pCJfPfbz-Ng
