### ISSUE TITLE
the cobblestone is fragile

### ISSUE THREAD

**Issue by Rom4ik01** [erzonline/community#60]
**Опиши баг**
Валун (булыжник) не имеет прочности

**Как повторить баг**
Напиши порядок действий приводящий к багу:
1. Подходиш к валуну
2. Включаеш режим копание
3. Направляеш робота в сторону валуна (булыжник)

**Ожидаемое поведение**
Валун (булыжник) должен ломатся с 5-100 ударов, при этом при каждом ударе должен смещается на одну клетку от робота

**Скриншоты и видео**
https://youtube.com/shorts/7iez26iJwQw?feature=share

**Smartphone (заполни на чем ты играл. когда нашел баг):**
 - Device: гнусмас а51 
 - OS: дроид 12
 - Version Erz 2022.5

**Дополнительные подробности/советы по исправлению**
Напиши тут.

**Comment by glebthebread** [comment]
Нужно точно добавить прочности валуну, чтобы не ломался сразу.
Оценить возможность его двигать.

**Comment by Rom4ik01** [comment]
Ломается с первого раза
https://youtube.com/shorts/MuE0h_MbeLk?feature=share

**Comment by Rom4ik01** [comment]
В части слома в версии 2022.6 стало норм, в части смещения так и стоит на месте (если не сломлен с удара то должнобыть смещение на одну клетку от робота если там свободная клетка и возвращаемся к если не сломлен с ...)
