### ISSUE TITLE
Digging bug

### ISSUE THREAD

**Issue by Lexmarkk** [erzonline/community#63]
Описание: при копании робота иногда отдёргивает назад, баг только на телефонах

Как повторить баг: копать с помощью джойстика на телефонах (см видео)

Ожидаемое поведение: робот должен копать плавно. 

видео: https://youtu.be/aI_JLcG5xgE

Desktop
 - OS: Windows 10

Smartphone
 - Device: honor 8s
 - OS: Android 9

:)

**Comment by glebthebread** [comment]
Нужно обсуждения с командой про повдение робота при копании.
