### ISSUE TITLE
Moving in meng bug

### ISSUE THREAD

**Issue by Lexmarkk** [erzonline/community#64]
**Описание**
Робот двигается, когда ты заходишь в меню и жмёшь WASD или стрелочки 

**Как повторить баг**
1. Нажимаешь кнопку "menu"
2. Нажимаешь кнопки управления 
3. Видишь ошибку

**Ожидаемое поведение**
Робот не должен двигаться, когда ты в меню

**Скриншоты и видео**
https://youtu.be/D7lZBcMI3qo

**Desktop**
 - OS: Windows 10

:)

**Comment by glebthebread** [comment]
Дубликат
