### ISSUE TITLE
control type pressing, not digging

### ISSUE THREAD

**Issue by Rom4ik01** [erzonline/community#66]
**Опиши баг**
Режим управления "тар" не копает.

**Как повторить баг**
Напиши порядок действий приводящий к багу:
1. Нажимаешь меню -> настройки -> режим упраления -> тап
2. Подходиш к породе
3. Кнопаеш на породу

**Ожидаемое поведение**
В режиме упраления "тар" при нажатии на породу он ее копает

**Скриншоты и видео**
https://youtube.com/shorts/F0Lx3htcESQ?feature=share

**Smartphone (заполни на чем ты играл. когда нашел баг):**
 - Device: самсунг а51
 - OS: андроид 12
 - Version Erz 2022.5

**Дополнительные подробности/советы по исправлению**
Напиши тут.

**Comment by Gitnube** [comment]
Duplicate  #32
