### ISSUE TITLE
boulder fall

### ISSUE THREAD

**Issue by Rom4ik01** [erzonline/community#68]
**Опиши баг**
Валун падает с ровной площадки

**Как повторить баг**
Напиши порядок действий приводящий к багу:
При копании тунеля с боку от волуна он туда падает

**Ожидаемое поведение**
Если валун стоит на твердой породе он не должен падать просто так в сторону

**Скриншоты и видео**
https://youtube.com/shorts/Fb8K48Zx_Es?feature=share

**Smartphone (заполни на чем ты играл. когда нашел баг):**
 - Device: самсунг а51
 - OS: андроид 12
 - Version Erz 2022.5

**Дополнительные подробности/советы по исправлению**
Напиши тут.

**Comment by glebthebread** [comment]
Скорее всего нужна отдельная логика для камней. Сейчас они работают как сыпучка.

**Comment by QA-game** [comment]
не актуально
