### ISSUE TITLE
autofill is missing

### ISSUE THREAD

**Issue by Rom4ik01** [erzonline/community#72]
**Опиши баг**
При выходе в главное меню  требует повторно ввести пароль

**Как повторить баг**
Напиши порядок действий приводящий к багу:
1. Вести логин
2. Вести пароль
3. Нажать войти (Login)
4. Дождаться загрузки
5. Нажать меню
6. нажать  Logout

**Ожидаемое поведение**
Заполнены строки логин и пароль

**Скриншоты и видео**
Как было
https://youtu.be/MJ7KtelYG_E
Как стало
https://youtu.be/VGIE6SOuhKs

**Smartphone (заполни на чем ты играл. когда нашел баг):**
 - Device: Самсунг А51
 - OS: Дроид12
 - Version Erz 2022.6

**Дополнительные подробности/советы по исправлению**
Напиши тут.

**Comment by glebthebread** [comment]
Будет переделано при разработчке фичи Авторизация.
