### ISSUE TITLE
Lava does not fall.

### ISSUE THREAD

**Issue by moralezWS** [erzonline/community#73]
**Опиши баг**
Лава и отвал потеряли свойства сыпучки.

**Как повторить баг**
Напиши порядок действий приводящий к багу:
1. Освобождаешь место под лавой/отвалом
2. Лава/отвал не падает

**Скриншоты и видео**
![изображение](https://user-images.githubusercontent.com/107573929/178816047-0707b7d5-fdf5-493f-b899-cf973557b7f9.png)

**Desktop (заполни на чем ты играл, когда нашел баг):**
OS: Windows 10, x64
Client Version: pre-Bastillia

**Comment by glebthebread** [comment]
Закрыт как дубликат
