### ISSUE TITLE
Main menu logo bug

### ISSUE THREAD

**Issue by Lexmarkk** [erzonline/community#79]
**Опиши баг**
Логотипы перекрывают собой добавленный недавно фон в главном меню

**Как повторить баг**
не нуждается в действиях со стороны игрока

**Ожидаемое поведение**
логотипы должны быть прозрачными

**Скриншоты и видео**
![Erz 14 07 2022 0_20_41](https://user-images.githubusercontent.com/108091440/178845716-0cf77c03-7f17-41d1-b48f-94f47a714d78.png)
![Erz 14 07 2022 0_20_43](https://user-images.githubusercontent.com/108091440/178845724-60407a1a-a52c-4828-822b-10af1228797d.png)
![Erz 14 07 2022 0_20_37](https://user-images.githubusercontent.com/108091440/178845726-d595bc3d-25ba-4798-968e-691915977fcd.png)

**Desktop**
 - OS: win 10
 - 
**Дополнительные подробности/советы по исправлению**
)))

**Comment by Rom4ik01** [comment]
![Screenshot_20220713-235237_Erz](https://user-images.githubusercontent.com/108063544/178972116-0a6018d1-c592-4cce-870c-34d94437bf39.jpg)

https://user-images.githubusercontent.com/108063544/178972129-2f2dd6ff-84bf-4b13-89f2-6831bce01fb6.mp4

**Comment by glebthebread** [comment]
Исправили
