### ISSUE TITLE
Login screen. Tab button.

### ISSUE THREAD

**Issue by moralezWS** [erzonline/community#8]
**Опиши баг**
Не работает кнопка Tab.
При нажатии кнопки ничего не происходит.

**Как повторить баг**
Напиши порядок действий приводящий к багу:
1. Выделяем поле воода логина или пароля
2. Нажимаем tab
3. Ничего не происходит

**Ожидаемое поведение**
При нажатии на Tab должно производиться переключение между полями ввода логина и пароля.

**Скриншоты и видео**
![изображение](https://user-images.githubusercontent.com/107573929/173890864-71cb281c-b424-4cdd-8539-9ae22ed871c6.png)

**Desktop (заполни на чем ты играл, когда нашел баг):**
 - OS: Windows 10, x64
 - Client Version: Release Okean

**Comment by ARyaskov** [comment]
В новой версии добавили переключение по TAB/SHIFT-TAB между полями ввода и кнопками на экране логина
<img width="547" alt="Screen Shot 2022-06-18 at 2 58 07 AM" src="https://user-images.githubusercontent.com/3934848/174413898-49ffbf0d-0fb1-4589-9562-5eff441a1bb7.png">

**Comment by moralezWS** [comment]
OS: Windows 10, x64
Client Version: Release GAVNO

баг:
Таб переключает не только между полями ввода но и между кнопками.
ожидание:
Таб должен переключать только между полями ввода логина/пароля.
Таб должен переключаться с последнего поля на первое.

**Comment by moralezWS** [comment]
Таб должен переключаться с последнего поля на первое.
Таб должен так же переключать на дискорд.

Client Version: pre-Bastillia
